# General
title: Serafins Blog
description: "Ersetzten Sie diese Platzhalterbeschreibung durch ihren eigenen Text. Wenn sie das vergessen, wäre es sehr peinlich!"
url: "https://seafinsblog.de"
markdown: kramdown
permalink: /:slugified_categories/:slug
excerpt_separator: "<!--more-->"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate