# General
title: Serafins Blog
description: "Ersetzten Sie diese Platzhalterbeschreibung durch ihren eigenen Text. Wenn sie das vergessen, wäre es sehr peinlich!"
url: "https://seafinsblog.de"
markdown: kramdown
permalink: pretty
excerpt_separator: "<!--more-->"
plugins:
  - jekyll-seo-tag